openapi: 3.0.0
info:
  title: Qdrant Query API
  version: 1.0.0
  description: Endpoints for exploring and querying Qdrant Cloud collections.

servers:
  - url: https://copilot-api-1.onrender.com
    description: Public server

paths:
  /collections:
    get:
      summary: List all collections
      description: Returns the names of all collections in the connected Qdrant Cloud instance.
      responses:
        '200':
          description: A list of collection names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /collections/{name}/sample:
    get:
      summary: Get sample points from a collection
      description: Returns up to 5 points with payloads from the specified collection.
      parameters:
        - in: path
          name: name
          required: true
          schema:
            type: string
          description: Name of the collection.
      responses:
        '200':
          description: A list of points with IDs and payloads
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    payload:
                      type: object

  /similar:
    get:
      summary: Find points similar to a given ID
      description: Returns a list of points similar to the given point ID in the specified collection using vector similarity.
      parameters:
        - in: query
          name: collection
          schema:
            type: string
            default: assets
          description: Name of the collection.
        - in: query
          name: id
          required: true
          schema:
            type: string
          description: ID of the reference point.
        - in: query
          name: k
          schema:
            type: integer
            default: 5
          description: Number of similar points to return.
      responses:
        '200':
          description: A list of similar points
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    score:
                      type: number
                    payload:
                      type: object
        '400':
          description: Missing or invalid parameters

